 sudo: required
 services:
  - docker

before_install:
  - docker build -t vit271202/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vit271202/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-421430921195"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
<<<<<<< HEAD
  secret_access_key: $AWS_SECRET_KEY
=======
  secret_access_key: "$AWS_SECRET_KEY"
>>>>>>> origin/main
