 sudo: required
 services:
  - docker

before_install:
  - docker build -t vit271202/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vit271202/docker-react npm run test -- --coverage
